<!--begin:: Global Optional Vendors -->
<script src="{{asset("vendors/general/jquery-form/dist/jquery.form.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/block-ui/jquery.blockUI.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/js/vendors/bootstrap-datepicker.init.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/js/vendors/bootstrap-timepicker.init.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-daterangepicker/daterangepicker.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-maxlength/src/bootstrap-maxlength.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-select/dist/js/bootstrap-select.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-switch/dist/js/bootstrap-switch.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/js/vendors/bootstrap-switch.init.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/select2/dist/js/select2.full.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/ion-rangeslider/js/ion.rangeSlider.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/typeahead.js/dist/typeahead.bundle.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/handlebars/dist/handlebars.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/inputmask/dist/jquery.inputmask.bundle.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/inputmask/dist/inputmask/inputmask.date.extensions.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/inputmask/dist/inputmask/inputmask.numeric.extensions.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/nouislider/distribute/nouislider.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/owl.carousel/dist/owl.carousel.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/autosize/dist/autosize.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/clipboard/dist/clipboard.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/dropzone/dist/dropzone.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/summernote/dist/summernote.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/markdown/lib/markdown.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-markdown/js/bootstrap-markdown.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/js/vendors/bootstrap-markdown.init.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/bootstrap-notify/bootstrap-notify.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/js/vendors/bootstrap-notify.init.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/jquery-validation/dist/jquery.validate.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/jquery-validation/dist/additional-methods.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/js/vendors/jquery-validation.init.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/toastr/build/toastr.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/raphael/raphael.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/morris.js/morris.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/chart.js/dist/Chart.bundle.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/vendors/jquery-idletimer/idle-timer.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/waypoints/lib/jquery.waypoints.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/counterup/jquery.counterup.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/es6-promise-polyfill/promise.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/sweetalert2/dist/sweetalert2.min.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/custom/js/vendors/sweetalert2.init.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/jquery.repeater/src/lib.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/jquery.repeater/src/jquery.input.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/jquery.repeater/src/repeater.js")}}" type="text/javascript"></script>
<script src="{{asset("vendors/general/dompurify/dist/purify.js")}}" type="text/javascript"></script>

<!--end:: Global Optional Vendors -->